name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  proto-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - uses: bufbuild/buf-setup-action@v1

      - name: Install protoc plugins
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Lint protos
        uses: bufbuild/buf-lint-action@v1

      - name: Generate code
        run: make generate

      - name: Verify generated code is up to date
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Generated code is not up to date. Run 'make generate' locally"
            git diff
            exit 1
          fi

      - name: Create tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
