name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  proto-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1

      - name: Lint protos
        uses: bufbuild/buf-lint-action@v1

      - name: Check breaking changes
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/grid-stream-org/grid-stream-protos.git#branch=main'
        if: github.event_name == 'pull_request'

      - name: Generate code
        uses: bufbuild/buf-generate-action@v1

      - name: Verify generated code is up to date
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Generated code is not up to date. Run 'buf generate' locally"
            exit 1
          fi
