name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  proto-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: bufbuild/buf-setup-action@v1

      - name: Lint protos
        uses: bufbuild/buf-lint-action@v1

      - name: Check breaking changes
        if: github.event_name == 'pull_request'
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/grid-stream-org/grid-stream-protos.git#branch=main'

      - name: Generate code
        run: make generate

      - name: Verify generated code is up to date
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Generated code is not up to date. Run 'make generate' locally"
            git diff
            exit 1
          fi

      - name: Create tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
